"""Generate LaTeX tables from CSV-derived summaries and supplied Protocol B results."""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd

import protocol_b as pb
from wsdata import (BENCH_ABBR, BENCHMARKS, DOMAINS, LANGUAGE_ABBR, LANGUAGE_TASKS,
                    POOL_LABEL, POOLS, STAGES, ZOO_LABEL, ZOO_ORDER, ZOO_TOKENS)

HEADER = ("% Generated by generate_workshop_artifacts.py. Do not edit by hand.\n")

PROTOCOL_A_NOTE = (
    "Protocol~A (Appendix Table~\\ref{tab:eval-settings-A}). "
    "Values are mean$_{\\pm\\text{SD}}$ over decoding seeds 42, 1234, and 2025."
)
PROTOCOL_B_NOTE = (
    "Protocol~B, the reasoning post-training protocol (Appendix Table~\\ref{tab:eval-settings-B}). "
    "Single seed, so no error bars are available."
)
STAGE_HEAD = {"base": "Base", "sft": "SFT", "dpo": "DPO"}


def _write(out: Path, name: str, body: str) -> Path:
    path = out / name
    path.write_text(HEADER + body)
    return path


def _ms(mean: float, sd: float) -> str:
    return f"{mean:.1f}$_{{\\pm{sd:.2f}}}$"


def _score_lookup(scores: pd.DataFrame, keys: dict, benchmark: str) -> tuple[float, float]:
    sel = scores
    for k, v in keys.items():
        sel = sel[sel[k] == v]
    row = sel[sel["benchmark"] == benchmark]
    return round(float(row["mean"].iloc[0]), 1), round(float(row["sd"].iloc[0]), 2)


# --------------------------------------------------------------------------------------
# Protocol A tables
# --------------------------------------------------------------------------------------


def factorial_summary(scores: pd.DataFrame, language: pd.DataFrame, out: Path) -> Path:
    """Main table: the 3 x 2 factorial, suite averages plus language understanding.

    Column one carries the web substrate, spanning its three rows.  Column two carries the
    front-loading factor and its contrast, ``no`` / ``yes`` / ``delta``.  Nothing is bold:
    this is a factorial, not a leaderboard, and emphasis would imply a winner.  The delta
    row is computed from the values the cells above it print, so subtracting by eye
    reproduces it exactly.
    """
    lang = language.set_index(["model_group", "front_loading", "context_length"])["language"]
    lines = [
        r"\begin{table}[t]", r"\centering",
        r"\caption{\textbf{Front-loading versus source licensing at 300B pre-training "
        r"tokens.} Each \emph{no} and \emph{yes} row is one 1.7B model trained under the "
        r"identical \texttt{open-sci-ref} configuration, differing only in the web substrate "
        r"and in whether the MixtureVitae instruction-and-reasoning subset is included. "
        r"Reasoning columns are the eleven-benchmark suite average under " + PROTOCOL_A_NOTE +
        r" Language columns are the eleven-task understanding suite on the corresponding "
        r"base checkpoint, single seed. $\Delta$ rows give the front-loading effect in "
        r"percentage points.}",
        r"\label{tab:factorial}", r"\small", r"\setlength{\tabcolsep}{3.5pt}",
        r"\resizebox{\linewidth}{!}{%",
        r"\begin{tabular}{llrrrrrrrr}", r"\toprule",
        r"& & \multicolumn{3}{c}{\textbf{Reasoning, 4K}} & "
        r"\multicolumn{3}{c}{\textbf{Reasoning, 16K}} & "
        r"\multicolumn{2}{c}{\textbf{Language}} \\",
        r"\cmidrule(lr){3-5}\cmidrule(lr){6-8}\cmidrule(lr){9-10}",
        r"\textbf{Web substrate} & \textbf{Front-loaded} & Base & SFT & DPO & Base & SFT & DPO"
        r" & 4K & 16K \\",
        r"\midrule",
    ]
    for pi, pool in enumerate(POOLS):
        if pi:
            lines.append(r"\addlinespace[0.35em]")
        label = POOL_LABEL[pool] + (r" \emph{(permissive)}" if pool == "MV" else "")
        cells = {}
        for fl in (False, True):
            row = []
            for ctx in (4096, 16384):
                for stage in STAGES:
                    row.append(_score_lookup(
                        scores,
                        dict(model_group=pool, front_loading=fl, context_length=ctx, stage=stage),
                        "__suite__"))
            # Round before storing, so the delta row equals the difference of the printed cells.
            row.append((round(float(lang.loc[(pool, fl, 4096)]), 1), None))
            row.append((round(float(lang.loc[(pool, fl, 16384)]), 1), None))
            cells[fl] = row
        first = r"\multirow{3}{*}{" + label + "}"
        for k, (fl, name) in enumerate(((False, "no"), (True, "yes"))):
            body = " & ".join(_ms(m, s) if s is not None else f"{m:.1f}" for m, s in cells[fl])
            lines.append(f"{first if k == 0 else ''} & {name} & {body} \\\\")
        delta = " & ".join(f"${b[0] - a[0]:+.1f}$" for a, b in zip(cells[False], cells[True]))
        lines.append(f" & $\\Delta$ & {delta} \\\\")
    lines += [r"\bottomrule", r"\end{tabular}}", r"\end{table}", ""]
    return _write(out, "factorial_summary.tex", "\n".join(lines))


def _perbenchmark_table(scores: pd.DataFrame, row_specs, caption: str, label: str,
                        keys_of, out: Path, name: str) -> Path:
    lines = [
        r"\begin{table}[t]", r"\centering", f"\\caption{{{caption}}}", f"\\label{{{label}}}",
        r"\scriptsize", r"\setlength{\tabcolsep}{3pt}",
        r"\resizebox{\linewidth}{!}{%",
        r"\begin{tabular}{l" + "r" * 12 + "}", r"\toprule",
        r"\textbf{Model} & " + " & ".join(f"\\textbf{{{BENCH_ABBR[b]}}}" for b in BENCHMARKS)
        + r" & \textbf{Avg} \\", r"\midrule",
    ]
    for entry in row_specs:
        if isinstance(entry, str):
            lines.append(r"\addlinespace[0.15em]")
            lines.append(r"\multicolumn{13}{l}{\textit{" + entry + r"}} \\")
            continue
        group_label, rows = entry
        lines.append(r"\addlinespace[0.2em]")
        for i, (row_label, keys) in enumerate(rows):
            k = keys_of(keys)
            vals = [_score_lookup(scores, k, b) for b in BENCHMARKS]
            avg = _score_lookup(scores, k, "__suite__")
            shown = group_label if i == 0 else ""
            name_cell = f"{shown}{row_label}"
            lines.append(name_cell + " & " + " & ".join(_ms(m, s) for m, s in vals)
                         + " & " + _ms(*avg) + r" \\")
        lines.append(r"\midrule")
    lines[-1] = r"\bottomrule"
    lines += [r"\end{tabular}}", r"\end{table}", ""]
    return _write(out, name, "\n".join(lines))


def factorial_perbenchmark(scores: pd.DataFrame, out: Path) -> Path:
    specs = []
    for ctx, tag in ((4096, ""), (16384, "-16K")):
        for pool in POOLS:
            for fl in (True, False):
                base = POOL_LABEL[pool].replace("Nemotron-CC-HQ", "Nemotron") + tag
                head = base + (" (FL)" if fl else "")
                rows = [("", dict(stage="base")),
                        (r"\quad $\to$ SFT", dict(stage="sft")),
                        (r"\quad $\to$ SFT $\to$ DPO", dict(stage="dpo"))]
                specs.append((head, [(rl, dict(model_group=pool, front_loading=fl,
                                               context_length=ctx, **k)) for rl, k in rows]))
    return _perbenchmark_table(
        scores, specs,
        r"Per-benchmark results for the 300B front-loading $\times$ web-substrate factorial. "
        r"(FL) marks the models whose pre-training mixture includes the MixtureVitae "
        r"instruction-and-reasoning subset. " + PROTOCOL_A_NOTE,
        "tab:factorial_perbenchmark", lambda k: k, out, "factorial_perbenchmark.tex")


def zoo_perbenchmark(scores: pd.DataFrame, out: Path, headline_only: bool = False) -> Path:
    """Phase 1 across the model zoo.

    ``headline_only`` keeps one context variant per model family, namely the 16K variant
    that the main text discusses, or the only variant available for the models that were
    not context extended.  The full table with both context variants goes to the appendix.
    """
    matched = ("MV", "Nemotron", "FineWeb-Edu", "DCLM", "Comma0.1")
    specs = []
    seen_matched = seen_external = False
    for group in ZOO_ORDER:
        if group in matched and not seen_matched:
            specs.append("Matched compute, 300B tokens, controlled comparison")
            seen_matched = True
        if group not in matched and not seen_external:
            specs.append("External open-weights references, 11--36T tokens, uncontrolled")
            seen_external = True
        contexts = sorted(scores[scores.model_group == group]["context_length"].unique())
        if headline_only:
            contexts = [max(contexts)]
        for ctx in contexts:
            head = ZOO_LABEL[group] + ("-16K" if ctx == 16384 else "")
            rows = [("", "base"), (r"\quad $\to$ SFT", "sft"), (r"\quad $\to$ SFT $\to$ DPO", "dpo")]
            specs.append((head, [(rl, dict(model_group=group, context_length=ctx, stage=st))
                                 for rl, st in rows]))
    if headline_only:
        caption = (
            r"\textbf{Phase~1 across the model zoo.} One context variant per model family, "
            r"namely the 16K variant where one exists and the released context "
            r"otherwise. The matched-compute models are trained on 300B tokens under the "
            r"\texttt{open-sci-ref} protocol, while SmolLM2, Qwen2.5, and Qwen3 use 11T, 18T, and 36T "
            r"tokens respectively and are uncontrolled upper references. Both context variants of "
            r"every model are in Table~\ref{tab:phase1_zoo_full}. " + PROTOCOL_A_NOTE)
        label, name = "tab:phase1_zoo", "phase1_zoo.tex"
    else:
        caption = (
            r"Phase~1 (Tulu3 SFT and DPO) across the model zoo at 1.7B scale, both context "
            r"variants. This is the complete version of Table~\ref{tab:phase1_zoo}. "
            + PROTOCOL_A_NOTE)
        label, name = "tab:phase1_zoo_full", "phase1_zoo_full.tex"
    return _perbenchmark_table(scores, specs, caption, label, lambda k: k, out, name)


def factorial_language(lang: pd.DataFrame, out: Path) -> Path:
    piv = lang.pivot_table(index=["model_group", "front_loading", "context_length"],
                           columns="task", values="performance")
    lines = [
        r"\begin{table}[t]", r"\centering",
        r"\caption{Language understanding for the twelve factorial checkpoints, on the "
        r"base and post-YaRN 16K checkpoints. This suite is scored by the LM Evaluation "
        r"Harness under its own settings and is not on either reasoning protocol. "
        r"Single seed. Accuracies in percent, "
        r"\texttt{acc\_norm} where the harness reports it, and shot counts are in "
        r"Table~\ref{tab:eval_settings_general}. Without front-loading, FineWeb-Edu and the "
        r"MixtureVitae substrate sit at chance on MMLU and CommonsenseQA.}",
        r"\label{tab:factorial_language}", r"\scriptsize", r"\setlength{\tabcolsep}{3pt}",
        r"\resizebox{\linewidth}{!}{%",
        r"\begin{tabular}{ll" + "r" * (len(LANGUAGE_TASKS) + 1) + "}", r"\toprule",
        r"\textbf{Model} & \textbf{FL} & "
        + " & ".join(f"\\textbf{{{LANGUAGE_ABBR[t]}}}" for t in LANGUAGE_TASKS)
        + r" & \textbf{Avg} \\", r"\midrule",
    ]
    for ctx, tag in ((4096, ""), (16384, "-16K")):
        for pool in POOLS:
            for fl in (True, False):
                row = piv.loc[(pool, fl, ctx)]
                vals = [row[t] for t in LANGUAGE_TASKS]
                name = POOL_LABEL[pool].replace("Nemotron-CC-HQ", "Nemotron") + tag
                lines.append(f"{name} & {'yes' if fl else 'no'} & "
                             + " & ".join(f"{v:.1f}" for v in vals)
                             + f" & {np.mean(vals):.1f}" + r" \\")
        lines.append(r"\midrule")
    lines[-1] = r"\bottomrule"
    lines += [r"\end{tabular}}", r"\end{table}", ""]
    return _write(out, "factorial_language.tex", "\n".join(lines))


def contrasts_table(contrasts: pd.DataFrame, out: Path) -> Path:
    fam_title = {"front-loading": "Front-loading effect, within web substrate",
                 "permissiveness": "Permissive minus non-permissive substrate, "
                                   "both front-loaded",
                 "interaction": "Interaction: front-loading effect, permissive minus "
                                "non-permissive"}
    lines = [
        r"\begin{table}[t]", r"\centering",
        r"\caption{All Protocol~A contrasts on the eleven-benchmark suite average, with "
        r"95\% paired item-level bootstrap intervals (2{,}000 replicates, items resampled "
        r"within benchmark, decoding seeds averaged first) and Benjamini--Hochberg adjusted "
        r"$q$-values computed within each family. Positive values favour front-loading in "
        r"the first block and the permissive substrate in the second. "
        r"Estimates are computed on unrounded item-level scores, so they can differ in the "
        r"final digit from the difference of the rounded values printed in "
        r"Table~\ref{tab:factorial}.}",
        r"\label{tab:contrasts}", r"\small", r"\setlength{\tabcolsep}{5pt}",
        r"\begin{tabular}{llrlr}", r"\toprule",
        r"\textbf{Contrast} & \textbf{Stage} & \textbf{Estimate} & \textbf{95\% CI} & "
        r"\textbf{$q$} \\", r"\midrule",
    ]
    for family in ("front-loading", "permissiveness", "interaction"):
        block = contrasts[contrasts.family == family]
        for ctx in (4096, 16384):
            lines.append(r"\multicolumn{5}{l}{\emph{" + fam_title[family]
                         + f", {'4K' if ctx == 4096 else '16K'} context" + r"}} \\")
            sub = block[block.context_length == ctx]
            for label in sorted(sub["label"].unique()):
                for stage in STAGES:
                    r = sub[(sub.label == label) & (sub.stage == stage)].iloc[0]
                    name = POOL_LABEL.get(label, label)
                    lines.append(
                        f"\\quad {name} & {STAGE_HEAD[stage]} & ${r.estimate:+.2f}$ & "
                        f"$[{r.lo:+.2f}, {r.hi:+.2f}]$ & "
                        + (r"$<0.001$" if r.q < 0.001 else f"${r.q:.3f}$") + r" \\")
            lines.append(r"\addlinespace[0.2em]")
        lines[-1] = r"\midrule"
    lines[-1] = r"\bottomrule"
    lines += [r"\end{tabular}", r"\end{table}", ""]
    return _write(out, "contrasts.tex", "\n".join(lines))


def domain_robustness(scores: pd.DataFrame, out: Path) -> Path:
    from wsdata import FACTOR_COLS, equal_domain_average, leave_one_domain_out, suite_average

    plain = suite_average(scores, FACTOR_COLS)
    equal = equal_domain_average(scores, FACTOR_COLS)
    loo = leave_one_domain_out(scores, FACTOR_COLS)

    def gap(frame: pd.DataFrame, ctx: int, stage: str, pool: str) -> float:
        sel = frame[(frame.context_length == ctx) & (frame.stage == stage)]
        mv = float(sel[(sel.model_group == "MV") & sel.front_loading]["mean"].iloc[0])
        other = float(sel[(sel.model_group == pool) & sel.front_loading]["mean"].iloc[0])
        return mv - other

    def eff(frame: pd.DataFrame, ctx: int, stage: str, pool: str) -> float:
        sel = frame[(frame.context_length == ctx) & (frame.stage == stage)
                    & (frame.model_group == pool)]
        return (float(sel[sel.front_loading]["mean"].iloc[0])
                - float(sel[~sel.front_loading]["mean"].iloc[0]))

    views = [("Suite average (11 tasks)", plain), ("Equal-domain average", equal)]
    views += [(f"Drop {d} domain", loo[loo.dropped == d]) for d in DOMAINS]

    lines = [
        r"\begin{table}[t]", r"\centering",
        r"\caption{Robustness of the two headline quantities to how the suite average is "
        r"weighted, at 16K context after Tulu3 SFT. The eleven-task macro average implicitly "
        r"weights math at 45\% and code at 27\%, and neither the front-loading effect nor the "
        r"substrate contrast depends on that weighting. " + PROTOCOL_A_NOTE + r"}",
        r"\label{tab:domain_robustness}", r"\small",
        r"\begin{tabular}{lrrrrr}", r"\toprule",
        r"& \multicolumn{3}{c}{\textbf{Front-loading effect}} & "
        r"\multicolumn{2}{c}{\textbf{Permissive $-$ non-permissive}} \\",
        r"\cmidrule(lr){2-4}\cmidrule(lr){5-6}",
        r"\textbf{Averaging view} & MV & Nemotron & FineWeb & vs.\ Nemotron & vs.\ FineWeb \\",
        r"\midrule",
    ]
    for name, frame in views:
        lines.append(
            f"{name} & "
            + " & ".join(f"${eff(frame, 16384, 'sft', p):+.1f}$" for p in POOLS)
            + " & "
            + " & ".join(f"${gap(frame, 16384, 'sft', p):+.1f}$"
                         for p in ("Nemotron", "FineWeb-Edu"))
            + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    return _write(out, "domain_robustness.tex", "\n".join(lines))


# --------------------------------------------------------------------------------------
# Protocol B tables
# --------------------------------------------------------------------------------------


def phase2_endpoints(out: Path) -> Path:
    lines = [
        r"\begin{table}[t]", r"\centering",
        r"\caption{Reasoning post-training endpoints. Identical OpenThoughts3-30K "
        r"post-training (30K samples, 5 epochs) is applied to every model, starting from the "
        r"checkpoint named in each block's first row. Starting checkpoints are re-evaluated "
        r"here, so these values are paired within the table and must not be compared against "
        r"the Phase~1 tables. " + PROTOCOL_B_NOTE + r"}",
        r"\label{tab:phase2_endpoints}", r"\scriptsize", r"\setlength{\tabcolsep}{3pt}",
        r"\resizebox{\linewidth}{!}{%",
        r"\begin{tabular}{l" + "r" * 12 + "}", r"\toprule",
        r"\textbf{Model} & " + " & ".join(f"\\textbf{{{b}}}" for b in pb.BENCH_ORDER)
        + r" & \textbf{Avg} \\", r"\midrule",
    ]
    current = None
    for group, row_label, is_start, vals in pb.PHASE2_ENDPOINTS:
        if group != current:
            if current is not None:
                lines.append(r"\midrule")
            current = group
            name = f"{group} {row_label}" if row_label != "base" else f"{group} (base)"
        else:
            name = r"\quad " + row_label.replace(r"\quad ", "")
        lines.append(name + " & " + " & ".join(f"{v:.1f}" for v in vals) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}}", r"\end{table}", ""]
    return _write(out, "phase2_endpoints.tex", "\n".join(lines))


def ot3_pretrain_ablation(out: Path) -> Path:
    lines = [
        r"\begin{table}[t]", r"\centering",
        r"\caption{\textbf{Removing OpenThoughts3 from pre-training removes the receptivity "
        r"to reasoning post-training.} Two 1.7B models pre-trained on 300B tokens that differ "
        r"only in whether the OpenThoughts3 subset is present, then given the identical "
        r"OT3-30K reasoning post-training. Architecture, schedule, token budget, long-context "
        r"extension, post-training recipe, and evaluation are held fixed. The intact base is "
        r"shown as a reference level, and the two post-trained endpoints are the comparison. "
        r"Bold marks the condition of interest, the model whose pre-training retained "
        r"OpenThoughts3. "
        + PROTOCOL_B_NOTE + r"}",
        r"\label{tab:ot3_pretrain_ablation}", r"\small", r"\setlength{\tabcolsep}{3.5pt}",
        r"\resizebox{\linewidth}{!}{%",
        r"\begin{tabular}{l" + "r" * 12 + "}", r"\toprule",
        r"\textbf{300B model} & " + " & ".join(f"\\textbf{{{b}}}" for b in pb.BENCH_ORDER)
        + r" & \textbf{Avg} \\", r"\midrule",
    ]
    for i, (label, vals) in enumerate(pb.OT3_PRETRAIN_ABLATION):
        if i == 1:
            lines.append(r"\midrule")
        cells = " & ".join(f"{v:.1f}" for v in vals)
        if i == 1:
            cells = " & ".join(f"\\textbf{{{v:.1f}}}" for v in vals)
        lines.append(label + " & " + cells + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}}", r"\end{table}", ""]
    return _write(out, "ot3_pretrain_ablation.tex", "\n".join(lines))


def heldout_reasoning(out: Path) -> Path:
    order = ["MixtureVitae", "Comma0.1", "FineWeb-Edu", "Nemotron-CC-HQ", "SmolLM2"]
    lines = [
        r"\begin{table}[t]", r"\centering",
        r"\caption{\textbf{The reasoning gain is not tied to OpenThoughts3.} Change in "
        r"MATH500 accuracy when each base's Tulu3 SFT checkpoint receives 30K samples from "
        r"one of four reasoning corpora, three of which are absent from every pre-training "
        r"mixture considered here. Brackets are 95\% paired bootstrap intervals over the same "
        r"500 problems. \textbf{Bold} marks a significant increase and \emph{italic} a "
        r"significant decrease after Benjamini--Hochberg correction. " + PROTOCOL_B_NOTE + r"}",
        r"\label{tab:heldout_reasoning}", r"\small", r"\setlength{\tabcolsep}{4pt}",
        r"\resizebox{\linewidth}{!}{%",
        r"\begin{tabular}{l" + "r" * len(pb.HELDOUT_CORPORA) + "}", r"\toprule",
        r"\textbf{Base} & " + " & ".join(f"\\textbf{{{c}}}" for c in pb.HELDOUT_CORPORA)
        + r" \\", r"\midrule",
    ]
    for base in order:
        cells = []
        for est, lo, hi, sig in pb.HELDOUT_MATH500[base]:
            txt = f"${est:+.1f}$ {{\\scriptsize$[{lo:+.1f}, {hi:+.1f}]$}}"
            if sig == "+":
                txt = f"$\\bm{{{est:+.1f}}}$ {{\\scriptsize$[{lo:+.1f}, {hi:+.1f}]$}}"
            elif sig == "-":
                txt = f"\\emph{{${est:+.1f}$}} {{\\scriptsize$[{lo:+.1f}, {hi:+.1f}]$}}"
            cells.append(txt)
        name = base
        lines.append(name + " & " + " & ".join(cells) + r" \\")
        if base == "MixtureVitae":
            lines.append(r"\midrule")
    lines += [r"\bottomrule", r"\end{tabular}}", r"\end{table}", ""]
    return _write(out, "heldout_reasoning.tex", "\n".join(lines))


def heldout_mv_grid(out: Path) -> Path:
    lines = [
        r"\begin{table}[t]", r"\centering",
        r"\caption{Full held-out reasoning grid for MixtureVitae: four reasoning corpora "
        r"applied from three starting checkpoints, with recipe, sample budget, and epoch "
        r"count held fixed so that only the identity of the reasoning corpus changes. "
        r"``--'' marks a benchmark that was not evaluated, and that row's average is taken "
        r"over the remaining ten. " + PROTOCOL_B_NOTE + r"}",
        r"\label{tab:heldout_mv_grid}", r"\scriptsize", r"\setlength{\tabcolsep}{3pt}",
        r"\resizebox{\linewidth}{!}{%",
        r"\begin{tabular}{l" + "r" * 12 + "}", r"\toprule",
        r"\textbf{Reasoning corpus} & " + " & ".join(f"\\textbf{{{b}}}" for b in pb.BENCH_ORDER)
        + r" & \textbf{Avg} \\",
    ]
    for stage in ("base", "sft", "dpo"):
        lines.append(r"\midrule")
        lines.append(r"\multicolumn{13}{l}{\emph{Starting from the "
                     + pb.STARTING_POINT_LABEL[stage] + r" checkpoint}} \\")
        start_avg = pb.HELDOUT_MV_GRID[stage][0][1][11]
        for label, vals in pb.HELDOUT_MV_GRID[stage]:
            cells = " & ".join("--" if v is None else f"{v:.1f}" for v in vals)
            if label == "starting checkpoint":
                lines.append(r"\quad \emph{starting checkpoint} & " + cells + r" \\")
            else:
                delta = vals[11] - start_avg
                lines.append(f"\\quad {label} & " + cells
                             + r"~" + f"{{\\scriptsize(${delta:+.1f}$)}}" + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}}", r"\end{table}", ""]
    return _write(out, "heldout_mv_grid.tex", "\n".join(lines))
